apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: "prometheus"
    prometheus: cluster
  name: exporter-kube-state
spec:
  groups:
    - name: kube-state-metrics.rules
      rules:
        - alert: DeploymentGenerationMismatch
          expr: kube_deployment_status_observed_generation != kube_deployment_metadata_generation
          for: 15m
          labels:
            severity: warning
          annotations:
            description:
              Observed deployment generation does not match expected one for
              deployment {{$labels.namespace}}/{{$labels.deployment}}
            summary: Deployment is outdated
        - alert: DeploymentReplicasNotUpdated
          expr:
            (((kube_deployment_status_replicas_updated != kube_deployment_spec_replicas)
            or (kube_deployment_status_replicas_available != kube_deployment_spec_replicas))
            unless (kube_deployment_spec_paused == 1))
            * on(deployment, namespace) group_right()
            label_replace(kube_deployment_labels, "app", "$1", "label_app", "(.+)")
          for: 15m
          labels:
            severity: warning
          annotations:
            description: Replicas are not updated and available for deployment {{$labels.namespace}}/{{$labels.deployment}}
            summary: Deployment replicas are outdated
        - alert: DaemonSetRolloutStuck
          expr:
            kube_daemonset_status_number_ready / kube_daemonset_status_desired_number_scheduled
            * 100 < 100
          for: 15m
          labels:
            severity: warning
          annotations:
            description:
              Only {{$value}}% of desired pods scheduled and ready for daemon
              set {{$labels.namespace}}/{{$labels.daemonset}}
            summary: DaemonSet is missing pods
        - alert: K8SDaemonSetsNotScheduled
          expr:
            kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled
            > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            description: A number of daemonsets are not scheduled.
            summary: Daemonsets are not scheduled correctly
        - alert: DaemonSetsMissScheduled
          expr: kube_daemonset_status_number_misscheduled > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            description:
              A number of daemonsets are running where they are not supposed
              to run.
            summary: Daemonsets are not scheduled correctly
        - alert: PodFrequentlyRestarting
          expr: max(increase(kube_pod_container_status_restarts_total[1h])) by (pod, namespace)
            * on(pod, namespace) group_right()
            label_replace(kube_pod_labels, "app", "$1", "label_app", "(.+)") > 5
          for: 10m
          labels:
            severity: warning
          annotations:
            description:
              Pod {{$labels.namespace}}/{{$labels.pod}} was restarted {{$value}}
              times within the last hour
            summary: Pod is restarting frequently
        - alert: JobFailed
          expr: kube_job_status_failed
            * on(job, namespace) group_right()
            label_replace(kube_job_labels, "app", "$1", "label_app", "(.+)") > 0
          labels:
            severity: warning
          annotations:
            description:
              Job {{$labels.namespace}}/{{$labels.job}} has failed
            summary: Job has failed
